[package]
name = "rustdoc-ember"
version = "0.1.0"
authors = ["steveklabnik <steve@steveklabnik.com>"]
license = "MIT/Apache-2.0"

[dependencies]
clap = "2"
env_logger = "0.4"
lazy_static = "0.2"
log = "0.3"

[build-dependencies]
glob = "0.2"
quote = "0.3"
